# Loader metadata
modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/eerussianguy/Decay-2012/issues"

# TFC
[[mods]]
    modId = "${modId}"
    version = "${modVersion}"
    displayName = "Decay 2012"
    credits = "EERussianguy"
    authors = "EERussianguy"
    description = '''Changes how decay looks in TFC.'''

# Dependencies
[[dependencies.decay_2012]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neoForgeVersionRange}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.decay_2012]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraftVersionRange}"
    ordering = "AFTER"
    side = "BOTH"

[[mixins]]
    config = "${modId}.mixins.json"

# We do our own biome coloring, see #2279
[mods."sodium:options"]
    "mixin.features.fast_biome_colors"=false  # Rubidium
    "mixin.features.render.world.sky"=false  # Embeddium, probably Sodium as well
